name: CI/CD Workflow

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  Requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Check:
    needs: Requirements
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Test:
    needs: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Staging:
    environment: Staging
    concurrency: Staging
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  Production:
    needs: Staging
    environment: Production
    concurrency: Production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
